# Customize the codemagic.yml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml for more information
workflows:
  imageCache-workflow:
    name: Pokedex Pipeline
    scripts:
      - name: CI/CD Started
        script: echo "Welcome to your Pokedex CICD setup!"
      - name: Pokedex
        script: | 
          xcodebuild build \
            -project "Pokedex.xcodeproj" \
            -scheme "Pokedex" \
            CODE_SIGN_INDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    publishing:
      email: 
        recipients:
        - heber.raz@gmail.com
